spring:
  application:
    name: DeliveryShipmentSystem

  datasource:
    url: jdbc:mysql://localhost:3308/deliveryspringboot
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mvc:
    locale: ar
    locale-resolver: fixed
    message-codes-resolver:
      format: PREFIX_ERROR_CODE
    dispatch-options-request: true
    content negotiation:
      favor-path-extension: false
    charset:
      default: UTF-8

server:
  port: 9090
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
