spring:
  application:
    name: DeliveryShipmentSystem

  datasource:
    url: jdbc:mysql://localhost:3308/deliveryspringboot
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 9090

